### ISSUE TITLE
Didn't parse the badges (despite no error)

### ISSUE THREAD

**Issue by TheLime1** [pemtajo/badge-readme#25]
im not getting any errors , but the badges wont show up

https://github.com/TheLime1/TheLime1/actions/runs/14781959264/job/41502606430

https://github.com/TheLime1/TheLime1/blob/main/.github/workflows/update-badges.yml

my Credly profile :  https://www.credly.com/users/thelime1  (same username as my Github username)

**Comment by TheLime1** [comment]
i downloaded the owner actions-results log and compared it with mine , we have the same results i dont know why it dosnt work on my profile

**Comment by Safnaj** [comment]
> I'm currently updating our code to accommodate the website's new HTML structure. The webscraping is currently not returning any data because of these changes.
> 
> I'll have it fixed as soon as possible. WIP

Commenting to get notified once it's done.

**Comment by link1905** [comment]
I noticed that they transitioned from raw html pages to API calls */users/username/badges?page=1&page_size=48&sort=rank*. Adapting to this change is pretty easy, but I have concerns about the legitimacy since these APIs are not officially documented.

**Comment by pemtajo** [comment]
Hey everyone,

First off, thank you for using this project and for your patience. I'm excited to let you know that a fix for this issue has been implemented and merged!

### The Root Cause
The main problem was that the Credly site now renders its content using JavaScript. This required a completely new approach to scrape the data correctly, as the badge information isn't in the initial HTML anymore. After some testing yesterday, the new method is working well.

### Important Changes
This new implementation comes with a few necessary changes:

**Default Order:** Badges are now sorted only from newest to oldest by default.
**Image Size:** To ensure reliability and use the default images from Credly, all badge images are now fixed at 80x80px. This avoids the need for extra HTML parsing.
**Badge Links Removed:** Unfortunately, the direct links to each badge are no longer available in the page's data after the JavaScript rendering. I've removed this feature to prevent broken links.

**Regarding the API vs. Web Scraping Discussion**
I did look into using the official API to make this more robust. However, I couldn't find a public endpoint that returns a user's badge list. Since this project's original goal was to practice web scraping, I'll be sticking with this method for now.

That said, I am completely open to improvements! If you find a better solution, especially one using an official API, please feel free to fork the repo and submit a Pull Request.

**Deployment Status**
The new code is already in the main branch, and the fix should be live for everyone within the next day.

Thanks again for your contributions and support!

**Comment by Safnaj** [comment]
Seems some issues is still there. ' See all ' button is not there in my case. I think this causing the issue. 
![Image](https://github.com/user-attachments/assets/b55e384e-983d-474a-9b42-a1d65298f5cd)

**Comment by pemtajo** [comment]
Thanks for the report. It seems the site's HTML structure was updated again.

I've just pushed a fix that should resolve this. Based on my tests, it's working as expected for now.

Please feel free to reopen it or create a new one if the problem reappears
